version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestP9Project
  gitServerName: rlakshitha0912
  gitUrl: https://github.com/rlakshitha0912/TestP9Project
  gitUsername: rlakshitha0912
  gitBranch: main
- name: AbhkPackages
  gitServerName: rlakshitha0912
  gitUrl: https://github.com/rlakshitha0912
  gitUsername: rlakshitha0912
  gitBranch: main
